#!/usr/bin/env bash
#!/usr/bin/env bash
mkdir -vp ./jmeter_test_result/MS_SQL/Simulation#1/TC#1 \
./jmeter_test_result/MS_SQL/Simulation#1/TC#2 \
./jmeter_test_result/MS_SQL/Simulation#1/TC#3 \
./jmeter_test_result/MS_SQL/Simulation#1/TC#4 \
./jmeter_test_result/MS_SQL/Simulation#1/TC#5 \
./jmeter_test_result/MS_SQL/Simulation#2/TC#1 \
./jmeter_test_result/MS_SQL/Simulation#2/TC#2 \
./jmeter_test_result/MS_SQL/Simulation#2/TC#3 \
./jmeter_test_result/MS_SQL/Simulation#2/TC#4 \
./jmeter_test_result/MS_SQL/Simulation#2/TC#5 \
./jmeter_test_result/MS_SQL/Simulation#3/TC#1 \
./jmeter_test_result/MS_SQL/Simulation#3/TC#2 \
./jmeter_test_result/MS_SQL/Simulation#3/TC#3 \
./jmeter_test_result/MS_SQL/Simulation#3/TC#4 \
./jmeter_test_result/MS_SQL/Simulation#3/TC#5 \
./jmeter_test_result/MS_SQL/Simulation#4/TC#1 \
./jmeter_test_result/MS_SQL/Simulation#4/TC#2 \
./jmeter_test_result/MS_SQL/Simulation#4/TC#3 \
./jmeter_test_result/MS_SQL/Simulation#4/TC#4 \
./jmeter_test_result/MS_SQL/Simulation#4/TC#5 \
./jmeter_test_result/PostgreSQL/Simulation#1/TC#1 \
./jmeter_test_result/PostgreSQL/Simulation#1/TC#2 \
./jmeter_test_result/PostgreSQL/Simulation#1/TC#3 \
./jmeter_test_result/PostgreSQL/Simulation#1/TC#4 \
./jmeter_test_result/PostgreSQL/Simulation#1/TC#5 \
./jmeter_test_result/PostgreSQL/Simulation#2/TC#1 \
./jmeter_test_result/PostgreSQL/Simulation#2/TC#2 \
./jmeter_test_result/PostgreSQL/Simulation#2/TC#3 \
./jmeter_test_result/PostgreSQL/Simulation#2/TC#4 \
./jmeter_test_result/PostgreSQL/Simulation#2/TC#5 \
./jmeter_test_result/PostgreSQL/Simulation#3/TC#1 \
./jmeter_test_result/PostgreSQL/Simulation#3/TC#2 \
./jmeter_test_result/PostgreSQL/Simulation#3/TC#3 \
./jmeter_test_result/PostgreSQL/Simulation#3/TC#4 \
./jmeter_test_result/PostgreSQL/Simulation#3/TC#5 \
./jmeter_test_result/PostgreSQL/Simulation#4/TC#1 \
./jmeter_test_result/PostgreSQL/Simulation#4/TC#2 \
./jmeter_test_result/PostgreSQL/Simulation#4/TC#3 \
./jmeter_test_result/PostgreSQL/Simulation#4/TC#4 \
./jmeter_test_result/PostgreSQL/Simulation#4/TC#5