#!/usr/bin/env bash
mkdir -vp ./jmeter_reports/MS_SQL/Simulation#1/TC#1 \
./jmeter_reports/MS_SQL/Simulation#1/TC#2 \
./jmeter_reports/MS_SQL/Simulation#1/TC#3 \
./jmeter_reports/MS_SQL/Simulation#1/TC#4 \
./jmeter_reports/MS_SQL/Simulation#1/TC#5 \
./jmeter_reports/MS_SQL/Simulation#2/TC#1 \
./jmeter_reports/MS_SQL/Simulation#2/TC#2 \
./jmeter_reports/MS_SQL/Simulation#2/TC#3 \
./jmeter_reports/MS_SQL/Simulation#2/TC#4 \
./jmeter_reports/MS_SQL/Simulation#2/TC#5 \
./jmeter_reports/MS_SQL/Simulation#3/TC#1 \
./jmeter_reports/MS_SQL/Simulation#3/TC#2 \
./jmeter_reports/MS_SQL/Simulation#3/TC#3 \
./jmeter_reports/MS_SQL/Simulation#3/TC#4 \
./jmeter_reports/MS_SQL/Simulation#3/TC#5 \
./jmeter_reports/MS_SQL/Simulation#4/TC#1 \
./jmeter_reports/MS_SQL/Simulation#4/TC#2 \
./jmeter_reports/MS_SQL/Simulation#4/TC#3 \
./jmeter_reports/MS_SQL/Simulation#4/TC#4 \
./jmeter_reports/MS_SQL/Simulation#4/TC#5 \
./jmeter_reports/PostgreSQL/Simulation#1/TC#1 \
./jmeter_reports/PostgreSQL/Simulation#1/TC#2 \
./jmeter_reports/PostgreSQL/Simulation#1/TC#3 \
./jmeter_reports/PostgreSQL/Simulation#1/TC#4 \
./jmeter_reports/PostgreSQL/Simulation#1/TC#5 \
./jmeter_reports/PostgreSQL/Simulation#2/TC#1 \
./jmeter_reports/PostgreSQL/Simulation#2/TC#2 \
./jmeter_reports/PostgreSQL/Simulation#2/TC#3 \
./jmeter_reports/PostgreSQL/Simulation#2/TC#4 \
./jmeter_reports/PostgreSQL/Simulation#2/TC#5 \
./jmeter_reports/PostgreSQL/Simulation#3/TC#1 \
./jmeter_reports/PostgreSQL/Simulation#3/TC#2 \
./jmeter_reports/PostgreSQL/Simulation#3/TC#3 \
./jmeter_reports/PostgreSQL/Simulation#3/TC#4 \
./jmeter_reports/PostgreSQL/Simulation#3/TC#5 \
./jmeter_reports/PostgreSQL/Simulation#4/TC#1 \
./jmeter_reports/PostgreSQL/Simulation#4/TC#2 \
./jmeter_reports/PostgreSQL/Simulation#4/TC#3 \
./jmeter_reports/PostgreSQL/Simulation#4/TC#4 \
./jmeter_reports/PostgreSQL/Simulation#4/TC#5