--Pre Run once

IF OBJECT_ID('dbo.TMP_CASE_TYPE__OFFICE_CODE', 'U') IS NOT NULL
  DROP TABLE dbo.TMP_CASE_TYPE__OFFICE_CODE
GO

CREATE TABLE TMP_CASE_TYPE__OFFICE_CODE (
	CASE_TYPE_NAME NVARCHAR(50),
	OFFICE_CODE NVARCHAR(50),
	OFFICE_ID NUMERIC(10,0))
GO

INSERT INTO dbo.TMP_CASE_TYPE__OFFICE_CODE(CASE_TYPE_NAME, OFFICE_CODE, OFFICE_ID)
SELECT
CT.CASE_TYPE_NAME,
OFC.OFFICE_CODE,
OFC.OFFICE_ID

	FROM
	dbo.CMS_CASE_FILE CF WITH (NOLOCK)
	LEFT OUTER JOIN dbo.CMS_CASE C WITH (NOLOCK) ON C.CASE_FILE_ID = CF.CASE_FILE_ID
	LEFT OUTER JOIN dbo.CMS_CASE_TYPE CT WITH (NOLOCK) ON C.CASE_TYPE_ID = CT.CASE_TYPE_ID
	LEFT OUTER JOIN dbo.CMS_CASE_TEMPLATE TMPL WITH (NOLOCK) ON C.CASE_TMPL_ID = TMPL.CASE_TMPL_ID
	LEFT OUTER JOIN dbo.CMS_LOCATION LOC WITH (NOLOCK) ON LOC.LOCATION_ID = C.LOCATION_ID
	LEFT OUTER JOIN dbo.CMS_CLIENT_HISTORY ch WITH (NOLOCK) ON ch.CASE_FILE_ID = cf.CASE_FILE_ID AND CH.CLIENT_HIST_CUR_CLIENT=1 AND CH.CLIENT_ROLE_ID=1
	LEFT OUTER JOIN dbo.CMS_CLIENT cli WITH (NOLOCK) ON cli.CLIENT_ID = ch.CLIENT_ID
	LEFT OUTER JOIN dbo.CMS_OFFICE OFC WITH (NOLOCK) ON CF.OFFICE_ID = OFC.OFFICE_ID
	LEFT OUTER JOIN dbo.CMS_ADDRESS ADR WITH (NOLOCK) ON CF.CASE_FILE_ID = ADR.CASE_FILE_ID
	LEFT OUTER JOIN dbo.CMS_COUNTY CN WITH (NOLOCK) ON ADR.COUNTY_ID = CN.COUNTY_ID
	LEFT OUTER JOIN dbo.CMS_STATE ST WITH (NOLOCK) ON ADR.STATE_ID = ST.STATE_ID
	LEFT OUTER JOIN dbo.CMS_STATE TMPLST WITH (NOLOCK) ON TMPL.STATE_ID = TMPLST.STATE_ID
	LEFT OUTER JOIN dbo.CMS_CASE_STATUS cs WITH (NOLOCK) ON c.CASE_ID = cs.CASE_ID AND cs.CASE_STAT_CUR_STAT=1
	LEFT OUTER JOIN dbo.CMS_STATUS_TYPE s WITH (NOLOCK)ON cs.STATUS_ID = s.STATUS_ID
	LEFT OUTER JOIN dbo.CMS_REFERRING_SYSTEM REF (NOLOCK) ON C.REF_SYS_ID=REF.REF_SYS_ID WHERE 1=1
AND (ISNULL(cli.SUPER_CODE_ID, -1) <> 3363 OR OFC.OFFICE_CODE NOT IN ('AZ', 'GA', 'KS', 'LA', 'MO', 'OIK', 'TX', 'VA') AND cli.SUPER_CODE_ID = 3363)
and CT.CASE_TYPE_NAME is not null
GROUP BY CT.CASE_TYPE_NAME,
OFC.OFFICE_CODE,
OFC.OFFICE_ID
having count(*) > 1000
order by count(*) desc