--Pre Run once
DO $$
DECLARE 
	v_object character varying(240);
	v_StartTime timestamp with time zone;
	v_EndTime timestamp with time zone;
	v_diff numeric(10);
BEGIN
	SELECT to_regclass('public.TMP_CASE_TYPE__OFFICE_CODE') INTO v_object;

IF v_object is not NULL THEN
  DROP TABLE public.TMP_CASE_TYPE__OFFICE_CODE;
END IF;

CREATE TABLE public.TMP_CASE_TYPE__OFFICE_CODE ( 
	CASE_TYPE_NAME character varying(50),  
	OFFICE_CODE character varying(50),
	OFFICE_ID NUMERIC(10,0));

v_StartTime := clock_timestamp();

	INSERT INTO public.TMP_CASE_TYPE__OFFICE_CODE(CASE_TYPE_NAME, OFFICE_CODE, OFFICE_ID)
	SELECT
	CT.CASE_TYPE_NAME,
	OFC.OFFICE_CODE,
	OFC.OFFICE_ID
	FROM   
	public.CMS_CASE_FILE CF  
	LEFT OUTER JOIN public.CMS_CASE C  ON C.CASE_FILE_ID = CF.CASE_FILE_ID  
	LEFT OUTER JOIN public.CMS_CASE_TYPE CT ON C.CASE_TYPE_ID = CT.CASE_TYPE_ID  
	LEFT OUTER JOIN public.CMS_CASE_TEMPLATE TMPL  ON C.CASE_TMPL_ID = TMPL.CASE_TMPL_ID  
	LEFT OUTER JOIN public.CMS_LOCATION LOC ON LOC.LOCATION_ID = C.LOCATION_ID   
	LEFT OUTER JOIN public.CMS_CLIENT_HISTORY ch ON ch.CASE_FILE_ID = cf.CASE_FILE_ID AND CH.CLIENT_HIST_CUR_CLIENT = 'true' AND CH.CLIENT_ROLE_ID=1     
	LEFT OUTER JOIN public.CMS_CLIENT cli  ON cli.CLIENT_ID = ch.CLIENT_ID  
	LEFT OUTER JOIN public.CMS_OFFICE OFC ON CF.OFFICE_ID = OFC.OFFICE_ID
	LEFT OUTER JOIN public.CMS_ADDRESS ADR  ON CF.CASE_FILE_ID = ADR.CASE_FILE_ID  
	LEFT OUTER JOIN public.CMS_COUNTY CN  ON ADR.COUNTY_ID = CN.COUNTY_ID  
	LEFT OUTER JOIN public.CMS_STATE ST ON ADR.STATE_ID = ST.STATE_ID
	LEFT OUTER JOIN public.CMS_STATE TMPLST  ON TMPL.STATE_ID = TMPLST.STATE_ID  
	LEFT OUTER JOIN public.CMS_CASE_STATUS cs  ON c.CASE_ID = cs.CASE_ID AND cs.CASE_STAT_CUR_STAT = 'true'
	LEFT OUTER JOIN public.CMS_STATUS_TYPE s ON cs.STATUS_ID = s.STATUS_ID
	LEFT OUTER JOIN public.CMS_REFERRING_SYSTEM REF  ON C.REF_SYS_ID=REF.REF_SYS_ID WHERE 1=1 
AND (COALESCE(cli.SUPER_CODE_ID, -1) <> 3363 OR OFC.OFFICE_CODE NOT IN ('AZ', 'GA', 'KS', 'LA', 'MO', 'OIK', 'TX', 'VA') AND cli.SUPER_CODE_ID = 3363) 
and CT.CASE_TYPE_NAME is not null
GROUP BY CT.CASE_TYPE_NAME,
OFC.OFFICE_CODE,
OFC.OFFICE_ID
having count(*) > 1000
order by count(*) desc;

v_EndTime := clock_timestamp();
select extract(second from (v_EndTime - v_StartTime)) into v_Diff;
raise notice '  --- v_Diff = %',  cast(v_Diff as character varying(20));

END$$